/* NovaPrint ortak etkileşim katmanı — framework'siz ve null-guard'lı */
(() => {
  const $=(s,c=document)=>c.querySelector(s), $$=(s,c=document)=>[...c.querySelectorAll(s)], root=document.documentElement;
  const menu=$('.menu-toggle'),nav=$('#mainNav');
  if(menu&&nav){menu.addEventListener('click',()=>{const open=nav.classList.toggle('open');menu.setAttribute('aria-expanded',String(open));menu.setAttribute('aria-label',open?'Menüyü kapat':'Menüyü aç')});$$('#mainNav a').forEach(a=>a.addEventListener('click',()=>{nav.classList.remove('open');menu.setAttribute('aria-expanded','false')}))}
  const saved=localStorage.getItem('novaprint-theme');if(saved)root.dataset.theme=saved;
  const theme=$('.theme-toggle');if(theme)theme.addEventListener('click',()=>{const dark=root.dataset.theme!=='dark';root.dataset.theme=dark?'dark':'light';localStorage.setItem('novaprint-theme',root.dataset.theme);theme.setAttribute('aria-label',dark?'Açık temayı aç':'Koyu temayı aç')});
  const lang=$('.lang-toggle');if(lang)lang.addEventListener('click',e=>{const en=e.currentTarget.textContent.trim()==='TR / EN';e.currentTarget.textContent=en?'EN / TR':'TR / EN';e.currentTarget.setAttribute('aria-label',en?'Dili Türkçe yap':'Dili İngilizce yap')});
  if('IntersectionObserver'in window){const reveal=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');reveal.unobserve(e.target)}}),{threshold:.12});$$('.reveal').forEach(el=>reveal.observe(el))}else $$('.reveal').forEach(el=>el.classList.add('visible'));
  const top=$('.to-top');if(top){addEventListener('scroll',()=>top.classList.toggle('visible',scrollY>600),{passive:true});top.addEventListener('click',()=>scrollTo({top:0,behavior:'smooth'}))}
  const filters=$$('.filter-bar button');filters.forEach(button=>button.addEventListener('click',()=>{const value=button.dataset.filter;filters.forEach(b=>{const active=b===button;b.classList.toggle('active',active);b.setAttribute('aria-pressed',String(active))});$$('.service-card').forEach(card=>card.classList.toggle('hidden',value!=='all'&&card.dataset.category!==value))}));
  const modal=$('#serviceModal');if(modal){let last;const close=()=>{modal.hidden=true;document.body.classList.remove('modal-open');last?.focus()},open=title=>{last=document.activeElement;$('#modalTitle').textContent=title;modal.hidden=false;document.body.classList.add('modal-open');$('.modal-close',modal)?.focus()};$$('[data-modal]').forEach(b=>b.addEventListener('click',()=>open(b.dataset.modal)));$('.modal-close',modal)?.addEventListener('click',close);modal.addEventListener('click',e=>{if(e.target===modal)close()});document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!modal.hidden)close()})}
  const band=$('.stats-band');if(band&&'IntersectionObserver'in window){let done=false;const obs=new IntersectionObserver(es=>{if(!es[0].isIntersecting||done)return;done=true;$$('[data-count]').forEach(el=>{const target=Number(el.dataset.count),start=performance.now(),duration=1200,prefix=el.dataset.prefix||'',suffix=el.dataset.suffix||'';function tick(now){const p=Math.min((now-start)/duration,1),v=Math.round(target*(1-Math.pow(1-p,3)));el.textContent=prefix+v.toLocaleString('tr-TR')+suffix;if(p<1)requestAnimationFrame(tick)}requestAnimationFrame(tick)})},{threshold:.3});obs.observe(band)}
  const form=$('#quoteForm');if(form){form.addEventListener('submit',e=>{e.preventDefault();const fields=$$('input,select,textarea',form),valid=fields.every(f=>f.checkValidity());if(!valid){form.reportValidity();return}const status=$('#formStatus');status.textContent='Talebiniz alındı. En kısa sürede sizinle iletişime geçeceğiz.';status.className='form-status success';form.reset()})}
  const cookie=$('.cookie-bar');if(cookie){if(localStorage.getItem('novaprint-cookie'))cookie.classList.add('hidden');else document.body.classList.add('cookie-visible');$$('.cookie-accept,.cookie-reject').forEach(b=>b.addEventListener('click',()=>{localStorage.setItem('novaprint-cookie',b.classList.contains('cookie-accept')?'accepted':'rejected');cookie.classList.add('hidden');document.body.classList.remove('cookie-visible')}))}
  $$('img').forEach(img=>img.addEventListener('error',()=>{img.classList.add('image-fallback');img.parentElement?.classList.add('image-fallback')}));
})();
